name: Build strapi docker image

on:
  workflow_dispatch:
  # Trigger the action when I create or push a `release/**` branch
  push:
    paths:
      - "apps/strapi/**"
    branches:
      - "main"

env:
  DOCKER_IMAGE_NAME: ${{ github.event.repository.name }}-strapi
  DOCKER_REGISTRY_URL: ghcr.io/${{ github.repository_owner }}

jobs:
  build_and_publish:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    # Runner to use
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Free up disk space
        run: ./scripts/free_disk_space.sh

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver

      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: apps/strapi/Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: |
            ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
